# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12cUFTF2SY9xYP-SteP7uJrINnW_LbrsG
"""

# ============================================================
# EXA-GUARD FINAL STREAMLIT APP
# ============================================================

import os
import textwrap

APP_PATH = "/content/app.py"

app_code = r'''
import os
import numpy as np
import streamlit as st
from PIL import Image
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import models, transforms
import matplotlib.pyplot as plt

# ============================================================
# CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="EXA-Guard",
    page_icon="🛡️",
    layout="wide"
)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

CHECKPOINT_DIR = "*"

VICTIM_PATH = os.path.join(
    CHECKPOINT_DIR,
    "victim_model.pth"
)

EXA_GUARD_PATH = os.path.join(
    CHECKPOINT_DIR,
    "exa_guard_model.pth"
)

IMAGE_SIZE = 112
NUM_CLASSES = 200

# ============================================================
# HEADER
# ============================================================

st.title("🛡️ EXA-Guard")
st.subheader(
    "Explainable Adversarial Analytics for Facial Biometric Systems"
)

st.markdown(
    """
    **Detection • Spatial Localization • Explainable AI**

    This prototype analyzes facial images for adversarial perturbations
    using FGSM, PGD and adversarial patch attacks.
    """
)

st.divider()

# ============================================================
# MODEL DEFINITIONS
# ============================================================

class FaceRecognitionModel(nn.Module):

    def __init__(self, num_classes):

        super().__init__()

        self.backbone = models.resnet18(
            weights=None
        )

        in_features = self.backbone.fc.in_features

        self.backbone.fc = nn.Linear(
            in_features,
            num_classes
        )

    def forward(self, x):

        return self.backbone(x)


class EXAGuardNetwork(nn.Module):

    def __init__(self):

        super().__init__()

        self.features = nn.Sequential(

            nn.Conv2d(
                3, 32,
                kernel_size=3,
                padding=1
            ),

            nn.BatchNorm2d(32),
            nn.ReLU(),

            nn.MaxPool2d(2),

            nn.Conv2d(
                32, 64,
                kernel_size=3,
                padding=1
            ),

            nn.BatchNorm2d(64),
            nn.ReLU(),

            nn.MaxPool2d(2),

            nn.Conv2d(
                64, 128,
                kernel_size=3,
                padding=1
            ),

            nn.BatchNorm2d(128),
            nn.ReLU(),

            nn.MaxPool2d(2),

            nn.Conv2d(
                128, 256,
                kernel_size=3,
                padding=1
            ),

            nn.BatchNorm2d(256),
            nn.ReLU()
        )

        self.detector = nn.Sequential(

            nn.AdaptiveAvgPool2d(1),

            nn.Flatten(),

            nn.Linear(256, 128),

            nn.ReLU(),

            nn.Dropout(0.3),

            nn.Linear(128, 1)
        )

        self.localization = nn.Sequential(

            nn.Conv2d(
                256, 64,
                kernel_size=3,
                padding=1
            ),

            nn.ReLU(),

            nn.Conv2d(
                64, 1,
                kernel_size=1
            )
        )

    def forward(self, x):

        features = self.features(x)

        detection = self.detector(features)

        localization = self.localization(features)

        localization = F.interpolate(
            localization,
            size=x.shape[-2:],
            mode="bilinear",
            align_corners=False
        )

        localization = torch.sigmoid(
            localization
        )

        return detection, localization


# ============================================================
# CHECKPOINT LOADER
# ============================================================

def load_checkpoint(model, path):

    checkpoint = torch.load(
        path,
        map_location=DEVICE
    )

    if isinstance(checkpoint, dict):

        if "model_state_dict" in checkpoint:

            state_dict = checkpoint["model_state_dict"]

        elif "state_dict" in checkpoint:

            state_dict = checkpoint["state_dict"]

        else:

            state_dict = checkpoint

    else:

        state_dict = checkpoint

    # Remove DataParallel prefix if present
    cleaned_state_dict = {}

    for key, value in state_dict.items():

        new_key = key

        if new_key.startswith("module."):

            new_key = new_key[7:]

        cleaned_state_dict[new_key] = value

    model.load_state_dict(
        cleaned_state_dict,
        strict=True
    )

    return model


# ============================================================
# MODEL LOADING
# ============================================================

@st.cache_resource
def load_models():

    victim = None
    exa_guard = None

    victim_status = False
    exa_status = False

    # Victim
    if os.path.exists(VICTIM_PATH):

        try:

            victim = FaceRecognitionModel(
                NUM_CLASSES
            )

            victim = load_checkpoint(
                victim,
                VICTIM_PATH
            )

            victim.to(DEVICE)
            victim.eval()

            victim_status = True

        except Exception as e:

            st.error(
                f"Victim model loading error: {e}"
            )

    # EXA-Guard
    if os.path.exists(EXA_GUARD_PATH):

        try:

            exa_guard = EXAGuardNetwork()

            exa_guard = load_checkpoint(
                exa_guard,
                EXA_GUARD_PATH
            )

            exa_guard.to(DEVICE)
            exa_guard.eval()

            exa_status = True

        except Exception as e:

            st.error(
                f"EXA-Guard model loading error: {e}"
            )

    return (
        victim,
        exa_guard,
        victim_status,
        exa_status
    )


victim_model, exa_guard_model, victim_ok, exa_ok = load_models()


# ============================================================
# SIDEBAR STATUS
# ============================================================

st.sidebar.header("System Status")

if victim_ok:

    st.sidebar.success(
        "✅ Victim Model Loaded"
    )

else:

    st.sidebar.error(
        "❌ Victim Model Missing"
    )


if exa_ok:

    st.sidebar.success(
        "✅ EXA-Guard Loaded"
    )

else:

    st.sidebar.error(
        "❌ EXA-Guard Missing"
    )


st.sidebar.write(
    f"Device: `{DEVICE}`"
)

st.sidebar.write(
    f"Victim checkpoint: `{os.path.exists(VICTIM_PATH)}`"
)

st.sidebar.write(
    f"EXA-Guard checkpoint: `{os.path.exists(EXA_GUARD_PATH)}`"
)

# ============================================================
# PREPROCESSING
# ============================================================

transform = transforms.Compose([

    transforms.Resize(
        (IMAGE_SIZE, IMAGE_SIZE)
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        [0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5]
    )
])


# ============================================================
# IMAGE CONVERSION
# ============================================================

def tensor_to_image(tensor):

    image = tensor.detach().cpu()

    image = image.squeeze(0)

    image = image * 0.5 + 0.5

    image = torch.clamp(
        image,
        0,
        1
    )

    image = image.permute(
        1, 2, 0
    ).numpy()

    return image


# ============================================================
# ATTACKS
# ============================================================

def generate_fgsm(
    model,
    image,
    epsilon=4 / 255
):

    x = image.clone().detach()

    x.requires_grad = True

    output = model(x)

    label = output.argmax(
        dim=1
    )

    loss = F.cross_entropy(
        output,
        label
    )

    model.zero_grad()

    loss.backward()

    adv = (
        x +
        epsilon *
        x.grad.sign()
    )

    adv = torch.clamp(
        adv,
        -1,
        1
    )

    return adv.detach()


def generate_pgd(
    model,
    image,
    epsilon=8 / 255,
    alpha=2 / 255,
    steps=5
):

    original = image.clone().detach()

    x = original.clone().detach()

    x.requires_grad = True

    with torch.no_grad():

        label = model(
            original
        ).argmax(
            dim=1
        )

    for _ in range(steps):

        x.requires_grad = True

        output = model(x)

        loss = F.cross_entropy(
            output,
            label
        )

        model.zero_grad()

        loss.backward()

        x = (
            x +
            alpha *
            x.grad.sign()
        ).detach()

        delta = torch.clamp(
            x - original,
            -epsilon,
            epsilon
        )

        x = torch.clamp(
            original + delta,
            -1,
            1
        ).detach()

    return x


def generate_patch(
    image,
    patch_size=28,
    intensity=0.9
):

    adv = image.clone().detach()

    _, _, h, w = adv.shape

    start_y = (
        h - patch_size
    ) // 2

    start_x = (
        w - patch_size
    ) // 2

    # normalized tensor:
    # intensity 0.9 -> approximately bright
    normalized_intensity = (
        intensity * 2
    ) - 1

    adv[
        :,
        :,
        start_y:start_y + patch_size,
        start_x:start_x + patch_size
    ] = normalized_intensity

    return adv


# ============================================================
# VICTIM PREDICTION
# ============================================================

def victim_prediction(
    model,
    image
):

    with torch.no_grad():

        output = model(image)

        probability = torch.softmax(
            output,
            dim=1
        )

        confidence, predicted = torch.max(
            probability,
            dim=1
        )

    return (
        predicted.item(),
        confidence.item()
    )


# ============================================================
# GRAD-CAM
# ============================================================

class GradCAM:

    def __init__(
        self,
        model,
        target_layer
    ):

        self.model = model

        self.target_layer = target_layer

        self.activations = None

        self.gradients = None

        self.forward_hook = (
            target_layer.register_forward_hook(
                self.save_activation
            )
        )

        self.backward_hook = (
            target_layer.register_full_backward_hook(
                self.save_gradient
            )
        )

    def save_activation(
        self,
        module,
        input,
        output
    ):

        self.activations = output

    def save_gradient(
        self,
        module,
        grad_input,
        grad_output
    ):

        self.gradients = grad_output[0]

    def generate(self, image):

        self.model.zero_grad()

        output, _ = self.model(image)

        score = output.mean()

        score.backward(
            retain_graph=True
        )

        gradients = self.gradients

        activations = self.activations

        weights = gradients.mean(
            dim=(2, 3),
            keepdim=True
        )

        cam = (
            weights *
            activations
        ).sum(
            dim=1,
            keepdim=True
        )

        cam = F.relu(cam)

        cam = F.interpolate(
            cam,
            size=image.shape[-2:],
            mode="bilinear",
            align_corners=False
        )

        cam = cam.squeeze().detach().cpu().numpy()

        cam_min = cam.min()

        cam_max = cam.max()

        cam = (
            cam - cam_min
        ) / (
            cam_max - cam_min + 1e-8
        )

        return cam


# ============================================================
# USER INTERFACE
# ============================================================

st.header("🔍 Adversarial Analysis")

uploaded_file = st.file_uploader(
    "Upload a facial image",
    type=[
        "jpg",
        "jpeg",
        "png"
    ]
)

attack_type = st.selectbox(
    "Select analysis mode",
    [
        "Clean Image",
        "FGSM",
        "PGD",
        "Adversarial Patch"
    ]
)

run_analysis = st.button(
    "🚀 Analyze Image",
    type="primary"
)


# ============================================================
# ANALYSIS
# ============================================================

if uploaded_file is not None:

    original_pil = Image.open(
        uploaded_file
    ).convert("RGB")

    original_tensor = transform(
        original_pil
    ).unsqueeze(0).to(
        DEVICE
    )

    st.subheader(
        "Uploaded Image"
    )

    st.image(
        original_pil,
        width=300
    )


    if run_analysis:

        if not victim_ok or not exa_ok:

            st.warning(
                """
                ⚠️ Trained model checkpoints are not available
                in the current Colab runtime.

                Please place:

                `victim_model.pth`

                and

                `exa_guard_model.pth`

                inside:

                `/content/exa_guard_checkpoints/`
                """
            )

            st.stop()


        # ----------------------------------------------------
        # Generate attack
        # ----------------------------------------------------

        if attack_type == "Clean Image":

            analysis_tensor = (
                original_tensor.clone()
            )

        elif attack_type == "FGSM":

            analysis_tensor = generate_fgsm(
                victim_model,
                original_tensor
            )

        elif attack_type == "PGD":

            analysis_tensor = generate_pgd(
                victim_model,
                original_tensor
            )

        elif attack_type == "Adversarial Patch":

            analysis_tensor = generate_patch(
                original_tensor
            )


        # ----------------------------------------------------
        # Victim prediction
        # ----------------------------------------------------

        predicted_class, confidence = (
            victim_prediction(
                victim_model,
                analysis_tensor
            )
        )


        # ----------------------------------------------------
        # EXA-Guard
        # ----------------------------------------------------

        with torch.enable_grad():

            detection_logits, localization = (
                exa_guard_model(
                    analysis_tensor
                )
            )

        attack_probability = torch.sigmoid(
            detection_logits
        ).item()

        localization_map = (
            localization[0, 0]
            .detach()
            .cpu()
            .numpy()
        )

        detected = (
            attack_probability >= 0.5
        )


        # ----------------------------------------------------
        # Grad-CAM
        # ----------------------------------------------------

        gradcam = GradCAM(
            exa_guard_model,
            exa_guard_model.features[-1]
        )

        with torch.enable_grad():

            cam = gradcam.generate(
                analysis_tensor
            )


        # ----------------------------------------------------
        # DISPLAY RESULTS
        # ----------------------------------------------------

        st.divider()

        st.header(
            "📊 Analysis Results"
        )

        col1, col2, col3 = st.columns(3)

        with col1:

            st.metric(
                "Attack Probability",
                f"{attack_probability * 100:.2f}%"
            )

        with col2:

            st.metric(
                "Victim Confidence",
                f"{confidence * 100:.2f}%"
            )

        with col3:

            if detected:

                st.error(
                    "⚠️ ATTACK DETECTED"
                )

            else:

                st.success(
                    "✅ CLEAN / BENIGN"
                )


        st.write(
            f"**Analysis Mode:** {attack_type}"
        )

        st.write(
            f"**Victim Predicted Class:** "
            f"{predicted_class}"
        )


        # ----------------------------------------------------
        # VISUALIZATION
        # ----------------------------------------------------

        analysis_image = tensor_to_image(
            analysis_tensor
        )

        col1, col2, col3 = st.columns(3)

        with col1:

            st.subheader(
                "Analyzed Image"
            )

            st.image(
                analysis_image,
                use_container_width=True
            )


        with col2:

            st.subheader(
                "EXA-Guard Localization"
            )

            fig1, ax1 = plt.subplots()

            ax1.imshow(
                analysis_image
            )

            ax1.imshow(
                localization_map,
                alpha=0.5,
                cmap="jet"
            )

            ax1.axis("off")

            st.pyplot(
                fig1,
                clear_figure=True
            )


        with col3:

            st.subheader(
                "Grad-CAM"
            )

            fig2, ax2 = plt.subplots()

            ax2.imshow(
                analysis_image
            )

            ax2.imshow(
                cam,
                alpha=0.5,
                cmap="jet"
            )

            ax2.axis("off")

            st.pyplot(
                fig2,
                clear_figure=True
            )


        # ----------------------------------------------------
        # TECHNICAL INFORMATION
        # ----------------------------------------------------

        with st.expander(
            "🔬 Technical Details"
        ):

            st.write(
                f"Device: {DEVICE}"
            )

            st.write(
                f"Input Size: {IMAGE_SIZE} × {IMAGE_SIZE}"
            )

            st.write(
                "Victim Model: ResNet-18"
            )

            st.write(
                f"Victim Classes: {NUM_CLASSES}"
            )

            st.write(
                "EXA-Guard: CNN-based detector + localization network"
            )

            if attack_type == "FGSM":

                st.write(
                    "FGSM epsilon: 4/255"
                )

            elif attack_type == "PGD":

                st.write(
                    "PGD epsilon: 8/255"
                )

                st.write(
                    "PGD alpha: 2/255"
                )

                st.write(
                    "PGD steps: 5"
                )

            elif attack_type == "Adversarial Patch":

                st.write(
                    "Patch size: 28 × 28"
                )


else:

    st.info(
        "👆 Upload a facial image to begin."
    )


# ============================================================
# FOOTER
# ============================================================

st.divider()

st.caption(
    "EXA-Guard | Explainable Adversarial Analytics "
    "for Facial Biometric Systems"
)
'''

with open(APP_PATH, "w", encoding="utf-8") as f:
    f.write(app_code)

print("✅ app.py created successfully")
print("Path:", APP_PATH)
print("Size:", os.path.getsize(APP_PATH), "bytes")

!pip -q install streamlit pyngrok

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

!pkill -f streamlit || true

!streamlit run /content/app.py \
    --server.port 8501 \
    --server.address 0.0.0.0 \
    > /content/streamlit.log 2>&1 &

import time
time.sleep(5)

print("===== STREAMLIT HEALTH CHECK =====")

import requests

try:
    r = requests.get(
        "http://127.0.0.1:8501/_stcore/health",
        timeout=5
    )

    print("✅ Streamlit is running")
    print("Status:", r.status_code)

except Exception as e:

    print("❌ Streamlit is NOT running")
    print(e)

!pkill -f cloudflared || true

!cloudflared tunnel \
    --url http://127.0.0.1:8501 \
    --no-autoupdate \
    > /content/cloudflare.log 2>&1 &

import time
import re

time.sleep(8)

with open(
    "/content/cloudflare.log",
    "r"
) as f:
    log = f.read()

print(log)

urls = re.findall(
    r"https://[a-zA-Z0-9.-]+\.trycloudflare\.com",
    log
)

if urls:

    print("\n" + "=" * 70)
    print("🌐 YOUR PUBLIC EXA-GUARD LINK")
    print("=" * 70)
    print(urls[-1])
    print("=" * 70)

else:

    print("❌ Cloudflare URL not found.")
    print("Run this cell again after a few seconds.")

!pkill -f streamlit || true

!streamlit run /content/app.py \
    --server.port 8501 \
    --server.address 0.0.0.0 \
    > /content/streamlit.log 2>&1 &

import time
time.sleep(5)

import requests

try:
    r = requests.get("http://127.0.0.1:8501/_stcore/health", timeout=5)
    print("✅ Streamlit running:", r.status_code)
except Exception as e:
    print("❌ Streamlit not running:", e)

!pkill -f cloudflared || true

!cloudflared tunnel \
    --url http://127.0.0.1:8501 \
    --no-autoupdate \
    > /content/cloudflare.log 2>&1 &

import time, re
time.sleep(8)

with open("/content/cloudflare.log", "r") as f:
    log = f.read()

urls = re.findall(r"https://[a-zA-Z0-9.-]+\.trycloudflare\.com", log)

if urls:
    print("🌐  PUBLIC LINK:")
    print(urls[-1])
else:
    print(log)

import os

print("CHECKPOINT FOLDER:")
print(os.path.exists("/content/exa_guard_checkpoints"))

if os.path.exists("/content/exa_guard_checkpoints"):
    print(os.listdir("/content/exa_guard_checkpoints"))

print("\nSEARCHING FOR .PTH FILES...")

for root, dirs, files in os.walk("/content"):
    for f in files:
        if f.endswith(".pth"):
            print(os.path.join(root, f))