# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12cUFTF2SY9xYP-SteP7uJrINnW_LbrsG
"""

# ============================================================
# EXA-GUARD + STREAMLIT + CLOUDFLARE TUNNEL
# ZERO-FABRICATION VERSION
# ============================================================

import os
import sys
import subprocess
import time
import requests
import re

# ============================================================
# 1. INSTALL STREAMLIT
# ============================================================

print("Installing Streamlit...")

subprocess.run(
    [sys.executable, "-m", "pip", "install", "-q", "streamlit", "pillow", "pandas", "numpy"],
    check=False
)

print("✅ Packages ready")


# ============================================================
# 2. CREATE STREAMLIT APP
# ============================================================

APP_CODE = r'''
import os
import streamlit as st
from PIL import Image

# ============================================================
# PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="EXA-Guard",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============================================================
# CSS
# ============================================================

CSS = """
<style>

.main {
    padding-top: 1rem;
}

.title-box {
    padding: 25px;
    border-radius: 15px;
    border: 1px solid rgba(128,128,128,0.25);
    margin-bottom: 20px;
}

.title-main {
    font-size: 2.2rem;
    font-weight: 700;
    margin-bottom: 8px;
}

.subtitle {
    font-size: 1rem;
    opacity: 0.75;
}

.metric-box {
    border: 1px solid rgba(128,128,128,0.25);
    border-radius: 12px;
    padding: 18px;
    text-align: center;
    min-height: 100px;
}

.metric-title {
    font-size: 0.9rem;
    opacity: 0.7;
}

.metric-value {
    font-size: 1.5rem;
    font-weight: 700;
    margin-top: 8px;
}

</style>
"""

st.markdown(CSS, unsafe_allow_html=True)


# ============================================================
# HEADER
# ============================================================

st.markdown("""
<div class="header">
    <div class="logo-icon">🛡️</div>

    <div class="title">
        EXA-Guard
    </div>

    <div class="subtitle">
        Explainable Adversarial Analytics for Facial Biometric Systems
    </div>

    <div class="subtitle">
        Detection • Localization • Explainability • Resilient Mitigation
    </div>
</div>
""", unsafe_allow_html=True
)


st.caption(
    "Research dashboard — experimental values are generated only "
    "from actual connected model/data. No fabricated results are used."
)


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.title("EXA-Guard")

st.sidebar.subheader("Research Configuration")

# ============================================================
# IMAGE UPLOAD
# ============================================================

st.sidebar.subheader("Input Image")

uploaded_file = st.sidebar.file_uploader(
    "Upload facial biometric image",
    type=[
        "jpg",
        "jpeg",
        "png",
        "bmp",
        "webp"
    ]
)

# ============================================================
attack_type = st.sidebar.selectbox(
    "Attack / Input Type",
    [
        "Benign / Clean Input",
        "FGSM",
        "PGD",
        "Carlini-Wagner",
        "Adversarial Patch",
        "Deepfake"
    ]
)

backbone = st.sidebar.selectbox(
    "Backbone",
    [
        "Actual Trained Model",
        "ResNet-50",
        "Swin Transformer",
        "Hybrid CNN + Transformer"
    ]
)

st.sidebar.info(
    "Attack and backbone selections are interface options only. "
    "They are not reported as experimental results until the "
    "corresponding trained model and attack pipeline are connected."
)


# ============================================================
# MODEL DETECTION
# ============================================================

def find_models():

    locations = [
        "/content",
        "/content/models",
        "/content/model",
        "/content/drive/MyDrive",
        "/content/drive/MyDrive/models",
        "/content/drive/MyDrive/EXA-Guard"
    ]

    extensions = (
        ".keras",
        ".h5",
        ".hdf5",
        ".pth",
        ".pt",
        ".onnx"
    )

    results = []

    for location in locations:

        if not os.path.exists(location):
            continue

        try:

            for root, dirs, files in os.walk(location):

                dirs[:] = [
                    d for d in dirs
                    if d not in [
                        ".cache",
                        ".config",
                        "node_modules"
                    ]
                ]

                for filename in files:

                    if filename.lower().endswith(extensions):

                        full_path = os.path.join(
                            root,
                            filename
                        )

                        if full_path not in results:
                            results.append(full_path)

        except Exception:
            pass

    return results


models = find_models()


if models:

    st.sidebar.success(
        f"{len(models)} model file(s) detected"
    )

    selected_model = st.sidebar.selectbox(
        "Detected Model",
        models
    )

else:

    st.sidebar.warning(
        "No trained model detected"
    )




# ============================================================
# TABS
# ============================================================

tab1, tab2, tab3, tab4 = st.tabs(
    [
        "Detection & Forensics",
        "Spatial Localization",
        "Quantitative XAI",
        "Architecture"
    ]
)


# ============================================================
# TAB 1
# ============================================================

with tab1:

    st.header("Detection & Forensics")

    if uploaded_file is None:

        st.info(
            "Please upload a facial biometric image "
            "from the sidebar."
        )

    else:

        try:

            image = Image.open(
                uploaded_file
            ).convert("RGB")

            left, right = st.columns(2)

            with left:

                st.subheader("Input Image")

                st.image(
                    image,
                    use_container_width=True
                )

            with right:

                st.subheader("Analysis")

                if not models:

                    st.warning(
                        "Prediction not available."
                    )

                    st.write(
                        "No trained model is connected."
                    )

                    st.write(
                        "The system will not generate "
                        "a fake prediction or confidence value."
                    )

                else:

                    st.info(
                        "Model file detected."
                    )

                    st.write(
                        "Automatic inference requires the exact "
                        "trained model architecture and preprocessing "
                        "pipeline used during training."
                    )

                    st.write(
                        "Inference is intentionally not guessed "
                        "from the model filename."
                    )

        except Exception as e:

            st.error(
                f"Image processing error: {e}"
            )


    st.divider()

    st.subheader("Experimental Output")

    c1, c2, c3, c4 = st.columns(4)

    with c1:

        st.markdown(
            """
            <div class="metric-box">
                <div class="metric-title">
                    Prediction
                </div>
                <div class="metric-value">
                    N/A
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

    with c2:

        st.markdown(
            """
            <div class="metric-box">
                <div class="metric-title">
                    Confidence
                </div>
                <div class="metric-value">
                    N/A
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

    with c3:

        st.markdown(
            """
            <div class="metric-box">
                <div class="metric-title">
                    Attack Detection
                </div>
                <div class="metric-value">
                    N/A
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

    with c4:

        st.markdown(
            """
            <div class="metric-box">
                <div class="metric-title">
                    Model Status
                </div>
                <div class="metric-value">
                    Not Connected
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )


# ============================================================
# TAB 2
# ============================================================

with tab2:

    st.header("Spatial Localization Engine")

    if uploaded_file is None:

        st.info(
            "Upload an image to begin localization."
        )

    else:

        st.warning(
            "No localization map has been generated."
        )

        st.write(
            "A valid Grad-CAM/localization map requires "
            "the actual trained model and target layer."
        )

        st.write(
            "Random or synthetic heatmaps are not used."
        )

        st.divider()

        st.metric(
            "IoU",
            "N/A"
        )

        st.caption(
            "IoU requires ground-truth localization annotations."
        )


# ============================================================
# TAB 3
# ============================================================

with tab3:

    st.header("Quantitative XAI Engine")

    xai_method = st.selectbox(
        "XAI Method",
        [
            "Grad-CAM",
            "Grad-CAM++",
            "LIME",
            "SHAP",
            "LRP"
        ]
    )

    st.write(
        "Selected XAI method:",
        xai_method
    )

    st.warning(
        "XAI output is unavailable until the actual trained "
        "model and compatible target layer are connected."
    )

    st.divider()

    a, b, c = st.columns(3)

    with a:

        st.metric(
            "AUC",
            "N/A"
        )

    with b:

        st.metric(
            "EER",
            "N/A"
        )

    with c:

        st.metric(
            "ACER",
            "N/A"
        )

    st.caption(
        "These metrics will be calculated from actual "
        "predictions and ground-truth labels only."
    )


# ============================================================
# TAB 4
# ============================================================

with tab4:

    st.header("EXA-Guard Architecture")

    st.markdown(
        """
### 1. Input
Facial biometric image

↓

### 2. Preprocessing
Resizing, normalization and tensor preparation

↓

### 3. Threat Analysis
Adversarial / spoofing / manipulated input analysis

↓

### 4. Deep Learning Model
CNN / Transformer / Hybrid architecture

↓

### 5. Detection
Benign vs manipulated/adversarial sample

↓

### 6. Explainability
Grad-CAM / Grad-CAM++ / LRP / LIME / SHAP

↓

### 7. Spatial Localization
Identification of influential image regions

↓

### 8. Quantitative Evaluation
Accuracy / Precision / Recall / F1 / AUC / EER / ACER / IoU

↓

### 9. Resilient Mitigation
Validated mitigation strategy
"""
    )

    st.divider()

    st.subheader("Research Integrity")

    integrity_points = [
        "No hard-coded accuracy.",
        "No hard-coded ACER.",
        "No hard-coded EER.",
        "No hard-coded AUC.",
        "No hard-coded IoU.",
        "No random confidence.",
        "No fabricated Grad-CAM.",
        "No fabricated attack-detection result.",
        "No fabricated experimental conclusion."
    ]

    for point in integrity_points:

        st.write(
            "✓",
            point
        )


# ============================================================
# DETECTED MODEL INFORMATION
# ============================================================

with st.expander("Model Files Detected"):

    if models:

        for model in models:
            st.code(model)

    else:

        st.write(
            "No trained model files detected."
        )


# ============================================================
# FOOTER
# ============================================================

st.divider()

st.caption(
    "EXA-Guard — research prototype. "
    "Experimental values are reported only from actual data/model outputs."
)

'''


APP_PATH = "/content/exa_guard_app.py"


print("✅ App file created:")
print(APP_PATH)


# ============================================================
# 3. STOP OLD STREAMLIT + CLOUDFLARE
# ============================================================

print("\nStopping previous processes...")

subprocess.run(
    "pkill -f 'streamlit run' || true",
    shell=True
)

subprocess.run(
    "pkill -f 'cloudflared tunnel' || true",
    shell=True
)

time.sleep(2)


# ============================================================
# 4. START STREAMLIT
# ============================================================

print("\n🚀 Starting Streamlit on port 8503...")




streamlit_cmd = (
    f"streamlit run {APP_PATH} "
    f"--server.port 8503 "
    f"--server.address 0.0.0.0 "
    f"--server.headless true "
    f"--browser.gatherUsageStats false"
)

streamlit_process = subprocess.Popen(
    streamlit_cmd,
    shell=True,
    stdout=streamlit_log,
    stderr=subprocess.STDOUT
)

time.sleep(8)


# ============================================================
# 5. STREAMLIT HEALTH CHECK
# ============================================================

print("\n===== STREAMLIT HEALTH CHECK =====")

try:

    response = requests.get(
        "http://127.0.0.1:8503/_stcore/health",
        timeout=5
    )

    if response.status_code == 200:

        print("✅ Streamlit is running")

    else:

        print(
            "❌ Streamlit returned:",
            response.status_code
        )

except Exception as e:

    print("❌ Streamlit is NOT running")
    print(e)

    print("\n===== STREAMLIT LOG =====")

    try:

        with open(
            "/content/streamlit.log",
            "r"
        ) as f:

            print(
                f.read()[-8000:]
            )

    except:
        pass


# ============================================================
# 6. INSTALL CLOUDFLARED
# ============================================================

print("\n☁️ Setting up Cloudflare Tunnel...")

cloudflared_path = "/content/cloudflared"

if not os.path.exists(cloudflared_path):

    subprocess.run(
        "wget -q "
        "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 "
        "-O /content/cloudflared",
        shell=True,
        check=False
    )

    subprocess.run(
        ["chmod", "+x", cloudflared_path],
        check=False
    )


# ============================================================
# 7. START CLOUDFLARE QUICK TUNNEL
# ============================================================

cloudflare_log_path = "/content/cloudflare.log"

cloudflare_log = open(
    cloudflare_log_path,
    "w"
)

print("🚀 Starting Cloudflare Tunnel...")

cloudflare_process = subprocess.Popen(
    [
        cloudflared_path,
        "tunnel",
        "--url",
        "http://127.0.0.1:8503",
        "--no-autoupdate"
    ],
    stdout=cloudflare_log,
    stderr=subprocess.STDOUT
)


# ============================================================
# 8. WAIT FOR PUBLIC URL
# ============================================================

print("\n⏳ Waiting for Cloudflare public URL...")

public_url = None

for i in range(30):

    time.sleep(2)

    try:

        with open(
            cloudflare_log_path,
            "r"
        ) as f:

            log_text = f.read()

        matches = re.findall(
            r"https://[a-zA-Z0-9-]+\.trycloudflare\.com",
            log_text
        )

        if matches:

            public_url = matches[-1]
            break

    except Exception:
        pass


# ============================================================
# 9. FINAL RESULT
# ============================================================

print("\n")
print("=" * 65)

if public_url:

    print("🎉 CLOUDFLARE TUNNEL IS READY")
    print("=" * 65)
    print()
    print("🌐 PUBLIC STREAMLIT LINK:")
    print()
    print(public_url)
    print()
    print("Open this link in your browser.")
    print()
    print("=" * 65)

else:

    print("❌ PUBLIC CLOUDFLARE LINK NOT FOUND")
    print("=" * 65)

    print("\n===== CLOUDFLARE LOG =====")

    try:

        with open(
            cloudflare_log_path,
            "r"
        ) as f:

            print(
                f.read()[-10000:]
            )

    except Exception as e:

        print(e)

print("\n===== FINAL STATUS =====")
print("Streamlit port : 8503")
print("App file       :", APP_PATH)
print("Research data  : NO PRESET VALUES")
print("Random values  : DISABLED")
print("Fake metrics   : DISABLED")
print("Cloudflare     :", "CONNECTED" if public_url else "FAILED")
